# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jngerng <jngerng@student.42kl.edu.my>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/14 20:47:56 by jngerng           #+#    #+#              #
#    Updated: 2022/11/14 20:47:56 by jngerng          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libftprintf.a
SRCS = srcs/ft_printf.c srcs/utlis.c srcs/help_int.c srcs/write_char_str.c \
		srcs/write_int.c srcs/write_hex.c srcs/help_hex.c
OBJS = $(SRCS:.c=.o)
INC = -I includes -I ../lib/includes
CFLAGS = -Wall -Wextra -Werror
CC = gcc

.c.o:
	${CC} ${CFLAGS} -c $< -o ${<:.c=.o} ${INC}

${NAME}: ${OBJS}
	$(MAKE) -C ../lib
	ar rc ${NAME} ${OBJS}

all: ${NAME}

clean:
	rm -f $(OBJS)

fclean: clean
	$(MAKE) fclean -C ../lib
	rm -f $(NAME)

re: fclean all
